---
# tasks file to start dockerproxy container 

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} the dockerproxy container"
  docker_container:
    name: dockerproxy
    image: tecnativa/docker-socket-proxy:{{ docker_dockerproxy_image | default('latest') }}
    networks:
      - name: traefik
    networks_cli_compatible: true
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    env:
        CONTAINERS: "1"
    restart_policy: unless-stopped
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    state: "{{ state | default('started') }}"
