---
# create all directories

- name: make sure {{ nextcloud_base_dir }} is present
  file:
    name: "{{ nextcloud_base_dir }}"
    owner: "{{ ansible_env.SUDO_USER | default('root') }}"
    group: "{{ ansible_env.SUDO_USER | default('root') }}"
    state: directory

- name: make sure {{ nextcloud_credential_store }} is present
  file: 
    name: '{{ nextcloud_credential_store }}'
    owner: "{{ ansible_env.SUDO_USER | default('root') }}"
    group: "{{ ansible_env.SUDO_USER | default('root') }}"
    mode:  0700
    state: directory

- name: make sure nextcloud directories are present
  file:
    name:  "{{ item.name }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    state: directory
  loop:
    - {name: "{{ nextcloud_config_dir }}", user: "33" , group: "33" }
    - {name: "{{ nextcloud_data_dir }}", user: "33" , group: "33" } 
    - {name: "{{ nextcloud_www_dir }}", user: "33" , group: "root" }
 
- name: make sure nextcloud nginx directories are present
  file:
    name: "{{ nextcloud_nginx_dir}}"
    owner: "33"
    group: "33"
    state: directory

- name: make sure {{ traefik_config_dir }} is present
  file:
    name:  "{{ traefik_config_dir }}"
    mode:  0750
    owner: root
    group: "{{ ansible_env.SUDO_USER | default('root') }}"
    state: directory

- name: Change label on Nextcloud Directorys for SELinux
  command: chcon -R -t container_file_t '{{ nextcloud_base_dir }}'

- name: Setsebool on rsync for SELinux
  command: setsebool -P rsync_full_access on