---
# Fedora CoreOS related tasks

- name: Set SELinux to enforcing permanently
  selinux:
    policy: targeted
    state: enforcing

- name: Set SELinux to enforcing until next reboot
  command: setenforce 1
  ignore_errors: true