---

- name: install onlyoffice app
  shell: '{{ docker_occ_cmd }} app:install onlyoffice'
  args:
    creates: '{{ nextcloud_www_dir }}/apps/onlyoffice'
  register: install_onlyoffice_app
  
- name: enable onlyoffice app
  shell: '{{ docker_occ_cmd }} app:enable onlyoffice'
  when: install_onlyoffice_app is changed

- name: setup onlyoffice app
  shell: '{{ docker_occ_cmd }} --no-warnings config:system:set onlyoffice {{ item }}'
  loop:
    - 'DocumentServerUrl --value="/ds-vpath/"'
    - 'DocumentServerInternalUrl --value="http://onlyoffice_documentserver/"'
    - 'StorageUrl --value="http://nginx/"'
  when: install_onlyoffice_app is changed
